# -*- mode: Makefile; -*-
# Copyright (c) 2011 Bitcoin Developers
# Distributed under the MIT/X11 software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

# Mac OS X makefile for iocoin
# Originally by Laszlo Hanyecz (solar@heliacal.net)
# Updated for DIONS 2.0: Homebrew and modern macOS support

# Compiler: Use clang++ (llvm-g++ is obsolete)
CXX=clang++

# Dependency paths: Prefer Homebrew on Apple Silicon, fallback to MacPorts
# Override by setting DEPSDIR environment variable
ifndef DEPSDIR
  # Detect Homebrew (Apple Silicon: /opt/homebrew, Intel: /usr/local)
  ifeq ($(shell test -d /opt/homebrew && echo 1), 1)
    DEPSDIR=/opt/homebrew
  else ifeq ($(shell test -d /usr/local/opt && echo 1), 1)
    DEPSDIR=/usr/local
  else
    # Fallback to MacPorts
    DEPSDIR=/opt/local
  endif
endif

# OpenSSL paths: Critical for DIONS 2.0 Phase 1
# Modern macOS does not ship OpenSSL headers, must use Homebrew/MacPorts
ifndef OPENSSL_PREFIX
  ifeq ($(shell test -d $(DEPSDIR)/opt/openssl@3 && echo 1), 1)
    OPENSSL_PREFIX=$(DEPSDIR)/opt/openssl@3
  else ifeq ($(shell test -d $(DEPSDIR)/opt/openssl@1.1 && echo 1), 1)
    OPENSSL_PREFIX=$(DEPSDIR)/opt/openssl@1.1
  else
    OPENSSL_PREFIX=$(DEPSDIR)
  endif
endif

INCLUDEPATHS= \
 -I"$(CURDIR)" \
 -I"$(CURDIR)"/obj \
 -I"$(OPENSSL_PREFIX)/include" \
 -I"$(DEPSDIR)/include" \
 -I"$(DEPSDIR)/include/db48" \
 -I"$(DEPSDIR)/opt/berkeley-db@4/include"

LIBPATHS= \
 -L"$(OPENSSL_PREFIX)/lib" \
 -L"$(DEPSDIR)/lib" \
 -L"$(DEPSDIR)/lib/db48" \
 -L"$(DEPSDIR)/opt/berkeley-db@4/lib"


LIBS= -dead_strip

ifdef STATIC
# Build STATIC if you are redistributing the iocoind binary
# Modern Homebrew Boost: libraries don't have -mt suffix
LIBS += \
 $(DEPSDIR)/lib/db48/libdb_cxx-4.8.a \
 $(DEPSDIR)/lib/libboost_system.a \
 $(DEPSDIR)/lib/libboost_filesystem.a \
 $(DEPSDIR)/lib/libboost_iostreams.a \
 $(DEPSDIR)/lib/libboost_serialization.a \
 $(DEPSDIR)/lib/libboost_program_options.a \
 $(DEPSDIR)/lib/libboost_thread.a \
 $(DEPSDIR)/lib/libssl.a \
 $(DEPSDIR)/lib/libcrypto.a \
 -lz
else
# Modern Homebrew Boost: libraries don't have -mt suffix
# Note: boost_system is header-only in modern Boost, no library needed
LIBS += \
 -ldb_cxx-4.8 \
 -lboost_filesystem \
 -lboost_iostreams \
 -lboost_serialization \
 -lboost_program_options \
 -lboost_thread \
 -lboost_chrono \
 -lssl \
 -lcrypto \
 -lz
endif

DEFS=-DMAC_OSX -DMSG_NOSIGNAL=0 -DBOOST_SPIRIT_THREADSAFE

# Detect architecture for platform-specific flags
ARCH := $(shell uname -m)

ifdef RELEASE
# Compile for maximum compatibility and smallest size.
# This requires that dependencies are compiled
# the same way.
ifeq ($(ARCH), x86_64)
  CFLAGS = -mmacosx-version-min=10.5 -arch x86_64 -O3 -msse2
else
  # Apple Silicon (arm64) or other architectures - omit x86-specific flags
  CFLAGS = -O3
endif
else
# Debug build
ifeq ($(ARCH), x86_64)
  CFLAGS = -g -msse2
else
  # Apple Silicon (arm64) - omit -msse2
  CFLAGS = -g
endif
endif

# ppc doesn't work because we don't support big-endian
CFLAGS += -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter \
    $(DEBUGFLAGS) $(DEFS) $(INCLUDEPATHS)

# OpenSSL 3.x compatibility: Suppress deprecation warnings
# Note: openssl_compat.h provides compatibility shims for deprecated APIs
# We suppress warnings only to allow compilation; behavior remains identical
CFLAGS += -Wno-deprecated-declarations

OBJS= \
    obj/alert.o \
    obj/version.o \
    obj/checkpoints.o \
    obj/netbase.o \
    obj/addrman.o \
    obj/crypter.o \
    obj/key.o \
    obj/db.o \
    obj/init.o \
    obj/irc.o \
    obj/keystore.o \
    obj/view.o \
    obj/main.o \
    obj/miner.o \
    obj/net.o \
    obj/state.o \
    obj/dions.o \
    obj/protocol.o \
    obj/bitcoinrpc.o \
    obj/rpcdump.o \
    obj/rpcnet.o \
    obj/rpcmining.o \
    obj/rpcwallet.o \
    obj/rpc-testgen.o \
    obj/rpcblockchain.o \
    obj/rpcrawtransaction.o \
    obj/script.o \
    obj/sync.o \
    obj/util.o \
    obj/wallet.o \
    obj/walletdb.o \
    obj/noui.o \
    obj/cubehash.o \
    obj/luffa.o \
    obj/aes_helper.o \
    obj/echo.o \
    obj/shavite.o \
    obj/simd.o \
    obj/blake.o\
    obj/bmw.o\
    obj/groestl.o\
    obj/jh.o\
    obj/keccak.o\
    obj/skein.o \
    obj/pbkdf2.o \
    obj/kernel.o

all: iocoind

# Modern LevelDB includes memenv in libleveldb.a
LIBS += $(CURDIR)/leveldb/libleveldb.a
DEFS += $(addprefix -I,$(CURDIR)/leveldb/include)
DEFS += $(addprefix -I,$(CURDIR)/leveldb/helpers)
OBJS += obj/txdb-leveldb.o
leveldb/libleveldb.a:
	@echo "Building LevelDB ..."; cd leveldb; make libleveldb.a libmemenv.a; cd ..
obj/txdb-leveldb.o: leveldb/libleveldb.a

# auto-generated dependencies:
-include obj/*.P

obj/build.h: FORCE
	/bin/sh ../share/genbuild.sh obj/build.h
version.cpp: obj/build.h
DEFS += -DHAVE_BUILD_INFO

obj/%.o: %.cpp
	$(CXX) -c $(CFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

obj/%.o: %.c
	$(CC) -c $(CFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

iocoind: $(OBJS:obj/%=obj/%)
	$(CXX) $(CFLAGS) -o $@ $(LIBPATHS) $^ $(LIBS)

clean:
	-rm -f iocoind
	-rm -f obj/*.o
	-rm -f obj/*.P
	-rm -f obj/build.h

FORCE:
